### ISSUE TITLE
Query parameter types are referenced but not generated

### ISSUE THREAD

**Issue by wied03** [mulesoft-labs/raml-for-jax-rs#271]
If I try and run the Maven plugin with the RAML below, the JAXRS generated interface references the `SourceSystem` and `DestinationType` query parameters properly but it does not create ENUMs for them so the generated code does not compile.

```yaml
#%RAML 1.0
title: some API
mediaType: application/json
version: v1
baseUri: http://localhost
securitySchemes:
  
/mappings:
  description: Maps stuff
  post:
    description: Create a mapping
    body:
      application/json:
        type: string
    responses: 
      201:
        body:
         application/json:
           type: string
  get:
    description: Retrieve a mapping
    queryParameters:
      source_system:
        enum: [SYS1, SYS2]
      source_system_id:
        type: string
      destination_system:
        enum: [SYS1, SYS2]
    responses: 
      200:
        description: Returns a single mapping that matches the criteria
        body:
          application/json:
            type: string
      404:
        description: No mappings were found with the given search criteria

```

```java
@Path("/mappings")
public interface Mappings {
  @POST
  @Consumes("application/json")
  PostMappingsResponse postMappings(LoanMapping entity);

  @GET
  @Produces("application/json")
  GetMappingsResponse getMappings(@QueryParam("source_system") SourceSystem sourceSystem, @QueryParam("source_system_id") String sourceSystemId, @QueryParam("destination_system") DestinationSystem destinationSystem);
}
```
pom.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.brady</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.raml</groupId>
        <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
        <version>2.0.1-SNAPSHOT</version>
        <configuration>
          <generateTypesWith>
            <value>jackson</value>
          </generateTypesWith>
        </configuration>
        <executions>
          <execution>
            <id>ourClasses</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <ramlFile>test.raml</ramlFile>
              <modelPackage>${project.groupId}.ramljaxrs.ourapi.models</modelPackage>
              <resourcePackage>${project.groupId}.ramljaxrs.ourapi.types</resourcePackage>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
      <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-client</artifactId>
        <version>2.25.1</version>
      </dependency>
  </dependencies>

  <pluginRepositories>
    <pluginRepository>
      <id>mulesoft-release</id>
      <name>mulesoft release repository</name>
      <layout>default</layout>
      <url>http://repository.mulesoft.org/releases/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
</project>
```

Command:
```
mvn clean compile
```

Output:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/brady/chrome_temp/raml-for-jax-rs/test/target/generated-sources/raml-to-jaxrs-maven-plugin/com/brady/ramljaxrs/ourapi/types/Mappings.java:[21,64] cannot find symbol
  symbol:   class SourceSystem
  location: interface com.brady.ramljaxrs.ourapi.types.Mappings
[ERROR] /Users/brady/chrome_temp/raml-for-jax-rs/test/target/generated-sources/raml-to-jaxrs-maven-plugin/com/brady/ramljaxrs/ourapi/types/Mappings.java:[21,180] cannot find symbol
  symbol:   class SourceSystem
  location: interface com.brady.ramljaxrs.ourapi.types.Mappings
```

**Comment by jpbelang** [comment]
Are you using the 2.0.1 branch ?

**Comment by wied03** [comment]
Tried in both 2.0.1-SNAPSHOT and 2.0.0 with the same effect

**Comment by wied03** [comment]
I built a snapshot today off of it yes.

sent from my mobile device

**Comment by wied03** [comment]
Ran it against 25969ab751d46e1992198c8c9cf2a9833a136109 today just to be sure and had the same problem (documented exact POM and error above)

**Comment by jpbelang** [comment]
We're releasing 2.0.1 soon.  That's the work you are seeing. :-)

You gave a pretty good example.  I'll get back to you soon. (soon == +/- the weekend :-) )

**Comment by wied03** [comment]
If I supply a type explicitly like below, it seems to assume the type of the query parameter is the same as the name of the query parameter:

RAML:
```yaml
#%RAML 1.0
title: some API
mediaType: application/json
version: v1
baseUri: http://localhost
securitySchemes:
types:
  SourceSystemType: !include some.raml
  
/mappings:
  description: Maps stuff
  post:
    description: Create a mapping
    body:
      application/json:
        type: string
    responses: 
      201:
        body:
         application/json:
           type: string
  get:
    description: Retrieve a mapping
    queryParameters:
      known_source_system: SourceSystemType
    responses: 
      200:
        description: Returns a single mapping that matches the criteria
        body:
          application/json:
            type: string
      404:
        description: No mappings were found with the given search criteria
```

Generated code looks like this:
```java
@GET
  @Produces("application/json")
  GetMappingsResponse getMappings(@QueryParam("known_system_type") KnownSystemType knownSystemType
```

**Comment by jpbelang** [comment]
I've pushed a trial of a fix for this.  Can you check it ?

**Comment by wied03** [comment]
It's generating a type now (in the types package) but doesn't import the type, so still fails.

**Comment by wied03** [comment]
Thanks for the quick commit though!

**Comment by jpbelang** [comment]
Ok.  I've fixed this.  I have a hangup though.  Within types, I create raml inline types as internal java types.  In resources, I create normal java types.  Not sure whether I should unifiy the approaches.

Just curious, do you have opinions ?

**Comment by wied03** [comment]
In the WSDL/CXF world (if I remember right), they seem to have settled on complexTypes being in their own file and not in some class.

If I extrapolate that to here, to me types that are defined with a name should be in their own class. If someone defines a type as an ENUM/object/etc. without a name, it logically seems more like an internal class to me (more along the lines of an XSD element without a separate named type). If someone uses a RAML library and names types in there, then those should be classes (or ENUMS) on their own.

If the the resources' query parameters are referencing types defined at the top level of the RAML, I think it would be good to use the same type (that's not inside another class) to avoid unnecessary ENUM mapping, etc.

To be honest, I haven't used the JAX-RS interfaces itself yet. I mainly use the generated classes in my unit tests for Mule flows.

In my tests I do test that query parameters are sent properly though so having them behave as I describe above might be helpful.

In a week or 2 I could roll up my sleeves and submit a PR once my immediately deadline is over if that helps.

**Comment by jpbelang** [comment]
Thanks, I think we mostly agree.

As to a PR:  wait.  We may be writing an external package like RamlDatatypesToJava, sort of like jsonschema2pojo.  This would leaveonly the resource generation in here.

BTW, did my push fix your issue ?

**Comment by wied03** [comment]
The inlined types work. If I refer to a type outside the resource from the query params, the JAXRS interface references the right type (and the type is under the models package) but it doesn't import the type, so compilation fails.

```yaml
#%RAML 1.0
title: some API
mediaType: application/json
version: v1
baseUri: http://localhost
securitySchemes:
types:
  destination_system:
    enum: [SYS3, SYS4]

/mappings:
  description: Maps stuff
  post:
    description: Create a mapping
    body:
      application/json:
        type: string
    responses:
      201:
        body:
         application/json:
           type: string
  get:
    description: Retrieve a mapping
    queryParameters:
      source_system:
        enum: [SYS1, SYS2]
      source_system_id:
        type: string
      destination_system: destination_system
    responses:
      200:
        description: Returns a single mapping that matches the criteria
        body:
          application/json:
            type: string
      404:
        description: No mappings were found with the given search criteria
```

DestinationSystem is what's not imported below.

```java
  @GET
  @Produces("application/json")
  GetMappingsResponse getMappings(@QueryParam("source_system") MappingsGetSourceSystem sourceSystem, @QueryParam("source_system_id") String sourceSystemId, @QueryParam("destination_system") DestinationSystem destinationSystem);
```

**Comment by jstoiko** [comment]
@jpbelang can you reproduce @wied03 last example? if so, let's move this to 2.1.1

**Comment by jpbelang** [comment]
I'll give it a shot tomorrow.

**Comment by c4rs10** [comment]
@wied03 I found a workaround with version 2.0.1: 
1. Define in an external file (e.g. a library) your **destination_system** and assign as type a second type **destination_systemType**
2. Write the enum in the **destination_systemType** within the same library

In the resource exists now the import of the Java enum **DestinationSystem**, which contains all data from  **destination_systemType**. 
The workaround has one deficit: The second Java enum DestinationSystemType is obsolet.
