### ISSUE TITLE
RAML-to-JAXRS CLI tool not generating model files in 2.1.x

### ISSUE THREAD

**Issue by JimPartin** [mulesoft-labs/raml-for-jax-rs#296]
trying to use ramltojaxrs cli tool on a 0.8 raml file. It will generate resources based on the -r flag (using 2.1.0 and 2.1.1), but will not generate any model files with the -m flag. Keeps crashing with errors. The -s flag also fails.

The older 1.3.x tool seems to have no problem.

Also tested with the RAML 1.0 torture test API.raml in the project, it also fails attempting to generate models.

Command:
```
java -jar raml-to-jaxrs-cli-2.1.1-SNAPSHOT-jar-with-dependencies.jar -d ./tmp -m org.foo.bar.models ./myRaml.raml

error:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
at com.squareup.javapoet.ClassName.(ClassName.java:52)
at com.squareup.javapoet.ClassName.(ClassName.java:43)
at com.squareup.javapoet.ClassName.get(ClassName.java:177)
at org.raml.jaxrs.generator.ResponseSupport.buildSupportClasses(ResponseSupport.java:53)
at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:113)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:116)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:72)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)
```

myRaml.raml:
```
#%RAML 0.8
title: thing1-oe-data-services-stuffs
baseUri: http://foo.bar.baz/thing1/oe/services/data/v1/stuffs

schemas:
- w00t: !include schemas/w00t-schema.json
- errorSchema: !include schemas/error-schema.json

/{var1}/op2/{var2}/op3/{var3}/op4/{var4}/op5/{op5}:
	get:
		description: la li lu le lo
		responses:
			200:
				body:
					application/json:
						schema: w00t
			404:
				body:
					application/json:
						schema: errorSchema
```

w00t-schema.json:
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "w00t",
	"description": "la li lu le lo",
	"type": "object",
	"properties": {
		"someId": {
			"type": "integer"
		},
		"someInt": {
			"type": "integer"
		},
		"aString": {
			"type": "string"
		},
		"anotherString": {
			"type": "string"
		},
		"blah": {
			"type": "string"
		},
		"anotherInt": {
			"type": "integer"
		}
	},
	"required": ["someId", "someInt","aString", "anotherString","blah"]
}
```

error-schema.json:
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Error",
	"description": "A Error Detail",
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"message": {
			"type": "string"
		}
	},
	"required": ["code", "message"]
}
```

**Comment by tarabola** [comment]
hello,

any solution?

**Comment by jpbelang** [comment]
Could you try with -r and -m ?  I might not default correctly.

**Comment by tarabola** [comment]
got the same

C:\EA\API\RAML\raml-for-jax-rs\raml-to-jaxrs\raml-to-jaxrs-cli>java -jar ./target/raml-to-jaxrs-cli-2.1.0-jar-with-dependencies.jar -d /tmp -r foo.bar ../examples/maven-examples/raml-defined-example/src/main/resources/dealerRestful.raml
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at org.raml.jaxrs.generator.v08.V08Finder.typesInBodies(V08Finder.java:106)
        at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:81)
        at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:78)
        at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:78)
        at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:78)
        at org.raml.jaxrs.generator.v08.V08Finder.findTypes(V08Finder.java:59)
        at org.raml.jaxrs.generator.CurrentBuild.constructClasses(CurrentBuild.java:259)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:106)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:72)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
        at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)

**Comment by jpbelang** [comment]
Could you try with the code on release 2.1.1 ?  I fixed this issue:

https://github.com/mulesoft-labs/raml-for-jax-rs/issues/265

Which looks a lot like yours.

**Comment by tarabola** [comment]
you forgot <module>posti-smartship</module> from maven-examples´s pom

**Comment by tarabola** [comment]
so, I removed posti-smartship module and finally it´s ok.

But still warnning 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by JimPartin** [comment]
Thanks, I'll check after his this hurricane blows through.

**Comment by jpbelang** [comment]
Hoping you are hypnotized by CNN and not in the path of the hurricane.  If you are, a sincere good luck.
